name: Rust Unit Tests

on:
  push:
    paths:
      - api/src/**
      - bot/src/**
      - scraper/src/**
      - utils/src/**
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test api
        working-directory: api
        run: cargo test --all --verbose

      - name: Test bot
        working-directory: bot
        run: cargo test --all --verbose

      - name: Test scraper
        working-directory: scraper
        run: cargo test --all --verbose

      - name: Test utils
        working-directory: utils
        run: cargo test --all --verbose